@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJpYXQiOjE3Mzg1NjY0NzV9.ubkmNlJVLdidNfDx4s04iIl4W_h63invbJ8xaaDpNOQ
//Adding 1st address
POST http://localhost:3000/api/address/
authorization: {{token}}
Content-Type: application/json

{
 "lineOne": "no xyz",
 "lineTwo": "abc street",
 "city": "Indore",
 "country": "India",
 "pincode": "689124"
}
###

//should throw error
POST http://localhost:3000/api/address/
authorization: {{token}}
Content-Type: application/json

{
 "lineOne": "a",
 "lineTwo": "b",
 "city": "c"
}
###

//should delete address
DELETE http://localhost:3000/api/address/6
authorization: {{token}}
Content-Type: application/json

###

//should return list of address belonging to the logged in user
GET http://localhost:3000/api/address/
authorization: {{token}}
Content-Type: application/json

###

//should update user
PUT http://localhost:3000/api/address/
authorization: {{token}}
Content-Type: application/json

{
 "defaultShippingAddress": 11,
 "defaultBillingAddress": 11
}