@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTczNzcxMjU2Nn0.B0f7s4owdUC_wKl1Evjxdarmi-xG6XvO-pzFHFx4Mxk

GET http://localhost:3000/api/auth/me/
authorization: {{token}}
Content-Type: application/json


###