@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJpYXQiOjE3Mzg1NzA4NDN9.UWwzaHHBJUZdpUdjKOG2j1BkvBBJqjCgBOko0bGzO9I

GET http://localhost:3000/api/auth/me/
authorization: {{token}}
Content-Type: application/json


###