@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJpYXQiOjE3Mzg1NzAxOTN9.gnUCq4B9FkEW4J3piXWVpfP9tjybe0YKytjerVH2kZA

GET http://localhost:3000/api/order/
authorization: {{token}}
Content-Type: application/json

###

POST http://localhost:3000/api/order/
authorization: {{token}}
Content-Type: application/json

{
  "order_id": "order_PrAllfC0u2zbn1",
  "payment_id": "abc"
  }
###

POST http://localhost:3000/api/order/
authorization: {{token}}
Content-Type: application/json

{
  "order_id": "order_PpAWuFynDK3jqm"
  }
###

GET http://localhost:3000/api/order/get/
authorization: {{token}}
Content-Type: application/json

###